version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db-market
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-market:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
     - 5432:5432
    volumes:
      - data_pg:/var/lib/postgresql/data
volumes:
  data_pg:
